title: miruvor
description: "Minimalist, fast, Markdown-first blog."
url: "https://dwork269-wq.github.io"
baseurl: ""    # user site → keep empty
markdown: kramdown
theme: null
permalink: /:title/
defaults:
  - scope: { path: "", type: posts }
    values: { layout: post, tags: [] }
